pipeline{

    agent any

    parameters{
        string(name : 'SPEC',defaultValue: "cypress/integration/**/**", description: "Enter the scripts path you want to execute")
        choice(name: 'BROWSER',choice: ['chrome','firefox'], description: "Choice the browser where you wnat to execute your scripts")
    }

    options{
        ansiColor('xterm')
    }
    stages{
        stage('Build'){
            echo "Build the application"
        }
        stage('Testing'){
            steps{
                sh "npm i"
                sh "npx cypress run -- browser ${BROWSER} --spec ${SPEC}"
            }
        }
        stage('Deploy'){
            echo "Deply the application"   
        }
    }

    post{
        always{
           publishHTML ([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'cypress/report',reportFiles: 'index.html', reportName: "HTML Report", reportTitles: ''])
        }
    }
}